### ISSUE TITLE
Darwin wrong launchctl load

### ISSUE THREAD

**Issue by garrylachman** [typicode/user-startup#1]
node_modules/user-startup/lib/startup/darwin.js
line 44:
cp.execSync('launchctl load ' + name);

must be 
cp.execSync('launchctl load ' + file);

you load the service plist file, then you can start the service by name

**Comment by typicode** [comment]
My bad, thank you :)

**Comment by garrylachman** [comment]
BTW, great lib, save me lot of work...

**Comment by typicode** [comment]
Thanks :)
