### ISSUE TITLE
Script doesn't start in Ubuntu

### ISSUE THREAD

**Issue by luizwbr** [typicode/user-startup#10]
I'm using this module to startup an script, but I found an error related to file permission.

I suggest add exec file permission to solve this problem, as I requested in #9

**Comment by typicode** [comment]
Hi @luizwbr,

Thanks for the PR and issue :)

I'm not reproducing on Ubuntu 18.04 though and can't find mention that the file should be executable ([spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)). Maybe it's related to something else.

**Comment by typicode** [comment]
Closing but feel free to comment, if you encounter this issue also in Ubuntu 18.04
