### ISSUE TITLE
Win64

### ISSUE THREAD

**Issue by garrylachman** [typicode/user-startup#2]
Win64 crash...
you must copy win32.js to win64.js or just load the same file for both platforms

**Comment by typicode** [comment]
What's your OS? AFAIK on Windows 8 64bit it works.

ˋos.platform()ˋ, which is used to select the file to load, actually returns ˋwin32ˋ on Windows 32bit and 64bit.

**Comment by garrylachman** [comment]
i test it on windows 2013 server its crashed....

**Comment by garrylachman** [comment]
on aws instance

**Comment by garrylachman** [comment]
i test it now on Windows 8 64bit...
still not working... i don`t have my debug code there, 
but its working for me only on windows 7 32bit

**Comment by typicode** [comment]
Do you have any error message?

What do you get when you run `require('os').platform()` on Windows 8 64bit?
I'll try on Windows 10 (upgraded recently).

On Windows it creates a vbs script in user's `AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup`. I don't know if Windows 2013 Server supports that.

**Comment by garrylachman** [comment]
i`m installing now NodeJS on Windows 8 64bit VPS...
i will try to debug it and post here the results...

**Comment by garrylachman** [comment]
Sorry... was bug in other part of my app

**Comment by typicode** [comment]
No worries, glad it's solved :)
